'use client'

import { useState } from 'react'
import { Copy, Check, FileCode2, ChevronDown, ChevronUp } from 'lucide-react'

const MODEL_LABELS = {
  claude:     'Claude · Architect',
  gpt:        'GPT · Reviewer',
  'gpt5.4o':  'GPT · Reviewer',
  codestral:  'Codestral · Implementer',
  gemini:     'Gemini · Refactor',
  perplexity: 'Perplexity · Researcher',
}

export default function OutputPreview({ outputs, sessionId }) {
  const [copied, setCopied] = useState(false)
  const [activeTab, setActiveTab] = useState(0)

  // `outputs` is an array of { taskId, model, taskType, content }
  const hasOutputs = outputs && outputs.length > 0
  const active = hasOutputs ? outputs[activeTab] ?? outputs[0] : null

  const handleCopy = async () => {
    if (!active?.content) return
    await navigator.clipboard.writeText(active.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // ── Empty state ─────────────────────────────────────────────────────────────
  if (!hasOutputs) {
    return (
      <div className="flex flex-col h-full">
        <div className="flex items-center gap-2 px-4 py-3 border-b border-gray-800">
          <FileCode2 className="w-4 h-4 text-gray-500" />
          <span className="text-sm font-medium text-gray-400">Preview</span>
        </div>
        <div className="flex-1 flex flex-col items-center justify-center text-center px-6 py-12">
          <div className="w-16 h-16 rounded-2xl bg-gray-800/60 border border-gray-700 flex items-center justify-center mb-4">
            <FileCode2 className="w-8 h-8 text-gray-600" />
          </div>
          <p className="text-gray-500 text-sm font-medium mb-1">No output yet</p>
          <p className="text-gray-600 text-xs leading-relaxed max-w-[200px]">
            Brief the council and the generated output will appear here.
          </p>
        </div>
      </div>
    )
  }

  // ── Output state ────────────────────────────────────────────────────────────
  const lines = (active?.content || '').split('\n')

  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800 flex-shrink-0">
        <div className="flex items-center gap-2">
          <FileCode2 className="w-4 h-4 text-indigo-400" />
          <span className="text-sm font-medium text-white">Preview</span>
          {sessionId && (
            <span className="text-xs text-gray-600 font-mono">#{sessionId.slice(0, 8)}</span>
          )}
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-800 hover:bg-gray-700 text-gray-300 hover:text-white rounded-lg text-xs font-medium transition-colors"
        >
          {copied ? (
            <><Check className="w-3.5 h-3.5 text-emerald-400" /><span className="text-emerald-400">Copied</span></>
          ) : (
            <><Copy className="w-3.5 h-3.5" />Copy</>
          )}
        </button>
      </div>

      {/* Tab bar (if multiple outputs) */}
      {outputs.length > 1 && (
        <div className="flex gap-1 px-3 py-2 border-b border-gray-800 overflow-x-auto flex-shrink-0">
          {outputs.map((out, i) => (
            <button
              key={i}
              onClick={() => setActiveTab(i)}
              className={`px-3 py-1 rounded-md text-xs font-medium whitespace-nowrap transition-colors ${
                i === activeTab
                  ? 'bg-indigo-600/30 text-indigo-300 border border-indigo-500/30'
                  : 'text-gray-500 hover:text-gray-300 hover:bg-gray-800'
              }`}
            >
              {out.taskType || `Output ${i + 1}`}
            </button>
          ))}
        </div>
      )}

      {/* Model attribution */}
      {active?.model && (
        <div className="px-4 py-2 border-b border-gray-800/50 flex-shrink-0">
          <p className="text-xs text-gray-500">
            Generated by <span className="text-gray-400">{MODEL_LABELS[active.model] || active.model}</span>
            {' · '}{lines.length} lines
          </p>
        </div>
      )}

      {/* Code content */}
      <div className="flex-1 overflow-auto min-h-0">
        <pre className="p-4 text-xs text-gray-300 font-mono leading-relaxed h-full">
          {active?.content || ''}
        </pre>
      </div>
    </div>
  )
}
